# Generated by Django 4.2.6 on 2023-10-26 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0002_rename_invites_invite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='org_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='plan_type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='primary_email',
            field=models.ForeignKey(db_column='email', null=True, on_delete=django.db.models.deletion.CASCADE, to='saas.user'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='stripe_customer_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='subscription_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
