# Generated by Django 4.2.6 on 2023-11-07 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0002_alter_user_is_email_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='firebase_user_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
