# Generated by Django 4.2.6 on 2023-11-09 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0003_alter_user_firebase_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='verify_key',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
